FROM ubuntu:latest
RUN apt-get update -y && apt-get install -y python python-pip
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY kubecalls.py ./
COPY hello.py ./
ENTRYPOINT [ "python" "./hello.py" ]

